# Generated by Django 3.2.9 on 2021-11-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
